# config/packages/coop_tilleuls_forgot_password.yaml
coop_tilleuls_forgot_password:
    password_token:
        class: App\Entity\PasswordToken # required
        expires_in: 1 day
        user_field: user
        serialization_groups: []
    user:
        class: App\Entity\User # required
        email_field: email
        password_field: password
